title: espaillato.github.io
description: Use github as bloging platform
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
